workflows:
  ios_build:
    name: Build iOS App
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build the app
        script: |
          xcodebuild \
            -project "primeChecker.xcodeproj" \
            -scheme "primeChecker" \
            -sdk iphoneos \
            -configuration Release \
            clean build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app
