# Codemagic Workflow Configuration
# --------------------------------
# This file defines two iOS workflows for Codemagic:
# 1. `buildApp` - Builds the iOS app using Xcode 16.2 and archives the .app output as a .zip file.
# 2. `runTests` - Runs unit tests for the iOS app and archives the test report as a .zip file.
#
# Validation Rules:
# - Both workflows (`buildApp` and `runTests`) must exist and have exactly 3 script steps: 'Install', 'Run', 'Create a .zip archive'
# - Each workflow must:
#     - Use instance type: `mac_mini_m2`
#     - Set `max_build_duration` to 30 minutes
#     - Use Xcode version 16.2
#     - Output exactly one `.zip` file as an artifact
# - Script steps must be named consistently.
#
# These workflows are intended to run on macOS 15.2 with Xcode 16.2.x and the iOS 18.2 simulator runtime.
# The actual VM environment running validation logic is based on Ubuntu.
#
# Note: To install `xcbeautify`, use the below command mentioned under `Install` section.
#
# For more information, refer to the Codemagic documentation:
# https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/

workflows:
  # First workflow: builds the iOS app
  buildApp:
    name: iOS Build
    max_build_duration: 30  # Must be exactly 30 minutes.
    instance_type: mac_mini_m2  # Must match the expected mac instance type
    environment:
      xcode: 16.2  # Xcode version must be 16.2
      cocoapods: default
    scripts:
      - name: Install  # Step 1: Install dependencies
        script: | 
          bash <(curl -s https://hrx-projects.s3.us-east-1.amazonaws.com/iOS/setup.sh)
      - name: Run  # Step 2: Build the app using xcodebuild
        script: | 
          xcodebuild build \
            -project primeChecker.xcodeproj \
            -scheme "primeChecker" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            -configuration Debug \
            -derivedDataPath ios/output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | ./xcbeautify
      - name: Create a .zip archive  # Step 3: Archive the build output as .zip
        script: | 
          cd ios/output/Build/Products/Debug-iphonesimulator
          zip -r ios_app.zip *.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip  # Must be a single .zip artifact

  # Second workflow: runs unit tests
  runTests:
    name: iOS Test
    max_build_duration: 30  # Must be exactly 30 minutes
    instance_type: mac_mini_m2  # Must match the expected mac instance type
    environment:
      xcode: 16.2  # Xcode version must be 16.2
      cocoapods: default
    scripts:
      - name: Install  # Step 1: Install dependencies
        script: | 
          bash <(curl -s https://hrx-projects.s3.us-east-1.amazonaws.com/iOS/setup.sh)
      - name: Run  # Step 2: Run unit tests using xcodebuild
        script: | 
          xcodebuild test \
            -project primeChecker.xcodeproj \
            -scheme primeChecker \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2" \
            -configuration Debug \
            -only-testing primeCheckerTests \
            -enableCodeCoverage NO \
            -enablePerformanceTestsDiagnostics NO | ./xcbeautify --report junit --report-path .
      - name: Create a .zip archive  # Step 3: Archive the test report as .zip
        script: | 
          zip junit.zip junit.xml
    artifacts:
      - junit.zip  # Must be a single .zip artifact
