workflows:
  buildApp:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install
        script: | 
          pod install
      - name: Run
        script: | 
          xcodebuild build \
            -workspace primeChecker.xcworkspace \
            -scheme "primeChecker" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            -configuration Debug \
            -derivedDataPath ios/output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | Pods/xcbeautify/xcbeautify
      - name: Create a .zip archive
        script: | 
          cd ios/output/Build/Products/Debug-iphonesimulator
          zip -r ios_app.zip *.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip
  runTests:
    name: iOS Test
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install
        script: | 
          pod install
      - name: Run
        script: | 
          xcodebuild test \
            -workspace primeChecker.xcworkspace \
            -scheme primeChecker \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2" \
            -configuration Debug \
            -only-testing primeCheckerTests \
            -enableCodeCoverage NO \
            -enablePerformanceTestsDiagnostics NO | Pods/xcbeautify/xcbeautify --report junit --report-path .
      - name: Create a .zip archive
        script: | 
          zip junit.zip junit.xml
    artifacts:
      - junit.zip
