workflows:
  simulator-native-ios:
    name: iOS simulator build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.0
      cocoapods: default
      groups:
        - appetize_io_secrets
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          # pod install
          echo "test"
      - name: Build the .app
        script: | 
          xcodebuild build \
            -project 'primeChecker.xcodeproj' \
            -scheme "primeChecker" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            -configuration Debug \
            -derivedDataPath ios/output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Create a .zip archive
        script: | 
          cd ios/output/Build/Products/Debug-iphonesimulator
          zip -r ios_app.zip primeChecker.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip
    publishing:
      scripts:
        - name: Publish App to Appetize
          script: | 
            zipPath="ios/output/Build/Products/Debug-iphonesimulator/ios_app.zip"
            echo $(curl --http1.1 https://$APPETIZE_API_TOKEN@api.appetize.io/v1/apps -F "file=@$zipPath" -F "platform=ios")
