workflows:
  buildApp:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install
        script: | 
          pod install
      - name: Run
        script: | 
          xcodebuild build \
            -project 'primeChecker.xcodeproj' \
            -scheme "primeChecker" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            -configuration Debug \
            -derivedDataPath ios/output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Create a .zip archive
        script: | 
          cd ios/output/Build/Products/Debug-iphonesimulator
          zip -r ios_app.zip primeChecker.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip
  runTests:
    name: iOS Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install
        script: | 
          pod install
      - name: Run
        script: | 
          open primeChecker.xcworkspace && \
          xcodebuild test \
            -scheme primeChecker \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0" \
            -configuration Debug \
            -only-testing primeCheckerTests \
            -enableCodeCoverage NO \
            -enablePerformanceTestsDiagnostics NO | Pods/xcbeautify/xcbeautify --report junit --report-path .
    artifacts:
      - junit.xml
